### PR TITLE
Fix some compiler warnings

### PR DESCRIPTION
**Pull request by mspensieri**

### CODE REVIEW

**Comment by epologee** [comment]
Hi @luisespinoza, with the release of iOS 7.1 the number of warnings has increased some, it'd be nice to see the library updated. @mspensieri seems to have nailed quite a few already. Would you be willing to merge in pull requests like these?

**Comment by epologee** [comment]
:+1: wow, thanks!

**Comment by epologee** [comment]
I took the liberty of `pod push`-ing the 1.0.3 spec. Thanks for tagging!

**Comment by luisespinoza** [comment]
Thanks!!

**Pull request merged**
